In [11]:
import pandas as pd

In [12]:


data = {
    'Customer_Name': ['Rahul Sharma', 'Priya Singh', 'Amit Kumar', 'Neha Verma', 'Rohan Mehta', 'Anjali Gupta'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Sales': [25000, 800, 55000, 15000, 500, 40000],
    'Payment_Method': ['Credit Card', 'Cash', 'Debit Card', 'Credit Card', 'Debit Card', 'Cash'],
    'City': ['Jaipur', 'Delhi', 'Mumbai', 'Jaipur', 'Delhi', 'Mumbai']
}

df = pd.DataFrame(data)

print(df)

  Customer_Name  Gender  Sales Payment_Method    City
0  Rahul Sharma    Male  25000    Credit Card  Jaipur
1   Priya Singh  Female    800           Cash   Delhi
2    Amit Kumar    Male  55000     Debit Card  Mumbai
3    Neha Verma  Female  15000    Credit Card  Jaipur
4   Rohan Mehta    Male    500     Debit Card   Delhi
5  Anjali Gupta  Female  40000           Cash  Mumbai

In [4]:
df["customer_name_len"] =df["Customer_Name"].apply(len)

In [5]:
df

  Customer_Name  Gender  Sales Payment_Method    City  customer_name_len
0  Rahul Sharma    Male  25000    Credit Card  Jaipur                 12
1   Priya Singh  Female    800           Cash   Delhi                 11
2    Amit Kumar    Male  55000     Debit Card  Mumbai                 10
3    Neha Verma  Female  15000    Credit Card  Jaipur                 10
4   Rohan Mehta    Male    500     Debit Card   Delhi                 11
5  Anjali Gupta  Female  40000           Cash  Mumbai                 12

In [7]:
df["Sales_category"] = df["Sales"].apply( lambda x :"High" if x > 20000 else "low")

In [8]:
df

,Customer_Name,Gender,Sales,Payment_Method,City,customer_name_len,Sales_category
0,Rahul Sharma,Male,25000,Credit Card,Jaipur,12,High
1,Priya Singh,Female,800,Cash,Delhi,11,low
2,Amit Kumar,Male,55000,Debit Card,Mumbai,10,High
3,Neha Verma,Female,15000,Credit Card,Jaipur,10,low
4,Rohan Mehta,Male,500,Debit Card,Delhi,11,low
5,Anjali Gupta,Female,40000,Cash,Mumbai,12,High

In [15]:
df["Gender_code"] = df["Gender"].map({"Male":1,"Female":0})

In [16]:
df

  Customer_Name  Gender  Sales Payment_Method    City  Gender_code
0  Rahul Sharma    Male  25000    Credit Card  Jaipur            1
1   Priya Singh  Female    800           Cash   Delhi            0
2    Amit Kumar    Male  55000     Debit Card  Mumbai            1
3    Neha Verma  Female  15000    Credit Card  Jaipur            0
4   Rohan Mehta    Male    500     Debit Card   Delhi            1
5  Anjali Gupta  Female  40000           Cash  Mumbai            0

In [17]:
df["Payment_Method"] = df["Payment_Method"].replace({"Credit Card" : "Card" , "Debit Card" :"Card"})

In [18]:
df

  Customer_Name  Gender  Sales Payment_Method    City  Gender_code
0  Rahul Sharma    Male  25000           Card  Jaipur            1
1   Priya Singh  Female    800           Cash   Delhi            0
2    Amit Kumar    Male  55000           Card  Mumbai            1
3    Neha Verma  Female  15000           Card  Jaipur            0
4   Rohan Mehta    Male    500           Card   Delhi            1
5  Anjali Gupta  Female  40000           Cash  Mumbai            0

In [19]:
df["sales_capped"] = df["Sales"].where(df["Sales"] <= 50000,50000)

In [20]:
df

,Customer_Name,Gender,Sales,Payment_Method,City,Gender_code,sales_capped
0,Rahul Sharma,Male,25000,Card,Jaipur,1,25000
1,Priya Singh,Female,800,Cash,Delhi,0,800
2,Amit Kumar,Male,55000,Card,Mumbai,1,50000
3,Neha Verma,Female,15000,Card,Jaipur,0,15000
4,Rohan Mehta,Male,500,Card,Delhi,1,500
5,Anjali Gupta,Female,40000,Cash,Mumbai,0,40000

In [15]:
df["Sales_adjusted"] =df["Sales"].where(df["Sales"] >= 1000,1000)
df

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Profit,Payment_Mode,Order_Status,Sales_adjusted
0,1001,Amit,Delhi,Electronics,Laptop,2,1200,200,UPI,Delivered,1200
1,1002,Priya,Mumbai,Furniture,Chair,1,800,120,Card,Delivered,1000
2,1003,Rahul,Jaipur,Clothing,T-Shirt,4,600,150,Cash,Pending,1000
3,1004,Neha,Delhi,Electronics,Mobile,2,1500,300,UPI,Delivered,1500
4,1005,Vikas,Pune,Furniture,Table,1,900,180,Card,Cancelled,1000
5,1006,Sneha,Mumbai,Clothing,Jeans,3,700,140,Cash,Delivered,1000
6,1007,Rohit,Jaipur,Electronics,Headphones,2,1100,220,UPI,Pending,1100
7,1008,Anjali,Delhi,Clothing,Shoes,5,750,160,Card,Delivered,1000
8,1009,Karan,Pune,Furniture,Sofa,1,1300,250,Cash,Cancelled,1300
9,1010,Pooja,Mumbai,Electronics,Tablet,2,1600,320,UPI,Delivered,1600
10,1011,Amit,Delhi,Clothing,Jacket,3,650,130,Card,Delivered,1000
11,1012,Priya,Mumbai,Furniture,Desk,2,1000,200,Cash,Pending,1000
12,1013,Rahul,Jaipur,Electronics,Laptop,1,1250,250,UPI,Delivered,1250
13,1014,Neha,Delhi,Clothing,T-Shirt,4,700,140,Card,Cancelled,1000
14,1015,Vikas,Pune,Furniture,Chair,2,850,170,Cash,Delivered,1000
15,1016,Sneha,Mumbai,Electronics,Mobile,3,1400,280,UPI,Pending,1400
16,1017,Rohit,Jaipur,Clothing,Shoes,5,900,180,Card,Delivered,1000
17,1018,Anjali,Delhi,Furniture,Table,1,1200,240,Cash,Delivered,1200
18,1019,Karan,Pune,Electronics,Headphones,2,1150,230,UPI,Cancelled,1150
19,1020,Pooja,Mumbai,Clothing,Jeans,4,800,160,Card,Pending,1000
20,1021,Amit,Delhi,Furniture,Sofa,2,1350,270,Cash,Delivered,1350
21,1022,Priya,Mumbai,Electronics,Tablet,3,1700,340,UPI,Delivered,1700
22,1023,Rahul,Jaipur,Clothing,Jacket,4,650,130,Card,Cancelled,1000
23,1024,Neha,Delhi,Furniture,Desk,1,950,190,Cash,Pending,1000
24,1025,Vikas,Pune,Electronics,Laptop,2,1450,290,UPI,Delivered,1450
25,1026,Sneha,Mumbai,Clothing,Shoes,5,1000,200,Card,Delivered,1000
26,1027,Rohit,Jaipur,Furniture,Chair,2,780,150,Cash,Pending,1000
27,1028,Anjali,Delhi,Electronics,Mobile,3,1550,310,UPI,Delivered,1550
28,1029,Karan,Pune,Clothing,T-Shirt,4,720,140,Card,Cancelled,1000
29,1030,Pooja,Mumbai,Furniture,Table,1,1100,220,Cash,Delivered,1100
30,1031,Amit,Delhi,Electronics,Headphones,2,1250,250,UPI,Pending,1250
31,1032,Priya,Mumbai,Clothing,Jeans,3,850,170,Card,Delivered,1000
32,1033,Rahul,Jaipur,Furniture,Sofa,1,600,120,Cash,Cancelled,1000
33,1034,Neha,Delhi,Electronics,Laptop,4,1600,320,UPI,Delivered,1600
34,1035,Vikas,Pune,Clothing,Jacket,2,900,180,Card,Delivered,1000
35,1036,Sneha,Mumbai,Furniture,Tablet,3,950,190,Cash,Pending,1000
36,1037,Rohit,Jaipur,Electronics,Shoes,5,1400,280,UPI,Cancelled,1400
37,1038,Anjali,Delhi,Clothing,Desk,2,780,150,Card,Delivered,1000
38,1039,Karan,Pune,Furniture,Mobile,1,1150,230,Cash,Pending,1150
39,1040,Pooja,Mumbai,Electronics,Chair,4,1300,260,UPI,Delivered,1300
40,1041,Amit,Delhi,Clothing,T-Shirt,3,700,140,Card,Delivered,1000
41,1042,Priya,Mumbai,Furniture,Headphones,2,1200,240,Cash,Cancelled,1200
42,1043,Rahul,Jaipur,Electronics,Table,5,1450,290,UPI,Pending,1450
43,1044,Neha,Delhi,Clothing,Jeans,1,820,160,Card,Delivered,1000
44,1045,Vikas,Pune,Furniture,Laptop,2,1050,210,Cash,Delivered,1050
45,1046,Sneha,Mumbai,Electronics,Sofa,4,1500,300,UPI,Pending,1500
46,1047,Rohit,Jaipur,Clothing,Tablet,3,900,180,Card,Cancelled,1000
47,1048,Anjali,Delhi,Furniture,Jacket,2,1350,270,Cash,Delivered,1350
48,1049,Karan,Pune,Electronics,Shoes,5,760,150,UPI,Pending,1000
49,1050,Pooja,Mumbai,Clothing,Desk,1,1100,220,Card,Delivered,1100

In [25]:
data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'City': ['Jaipur', 'Delhi', 'Jaipur', 'Mumbai', 'Delhi',
             'Mumbai', 'Jaipur', 'Delhi', 'Mumbai', 'Jaipur'],
    'Category': ['Electronics', 'Clothing', 'Clothing', 'Electronics',
                 'Electronics', 'Clothing', 'Electronics', 'Clothing',
                 'Electronics', 'Clothing'],
    'Sales': [25000, 12000, 15000, 30000, 22000,
              18000, 28000, 10000, 35000, 14000]
}

df = pd.DataFrame(data)

In [26]:
df

   Order_ID    City     Category  Sales
0       101  Jaipur  Electronics  25000
1       102   Delhi     Clothing  12000
2       103  Jaipur     Clothing  15000
3       104  Mumbai  Electronics  30000
4       105   Delhi  Electronics  22000
5       106  Mumbai     Clothing  18000
6       107  Jaipur  Electronics  28000
7       108   Delhi     Clothing  10000
8       109  Mumbai  Electronics  35000
9       110  Jaipur     Clothing  14000

In [29]:
df.groupby("Category")["Sales"].sum()

Category
Clothing        69000
Electronics    140000
Name: Sales, dtype: int64

In [30]:
df.groupby("City")["Sales"].sum()

City
Delhi     44000
Jaipur    82000
Mumbai    83000
Name: Sales, dtype: int64

In [31]:
df.groupby("City")[["Category","Sales"]].sum()

                                      Category  Sales
City
Delhi              ClothingElectronicsClothing  44000
Jaipur  ElectronicsClothingElectronicsClothing  82000
Mumbai          ElectronicsClothingElectronics  83000

In [32]:
df = pd.DataFrame({
    "Category": ["A", "A", "B", "B", "C"],
    "Sales": [100, 200, 150, 250, 300],
    "Quantity": [2, 4, 3, 5, 6],
    "Profit": [20, 40, 30, 50, 60]
})

In [33]:
df

  Category  Sales  Quantity  Profit
0        A    100         2      20
1        A    200         4      40
2        B    150         3      30
3        B    250         5      50
4        C    300         6      60

In [34]:
df.groupby("Category").agg({"Sales":["sum","mean","max"],"Quantity":"sum"})

         Sales             Quantity
           sum   mean  max      sum
Category
A          300  150.0  200        6
B          400  200.0  250        8
C          300  300.0  300        6

In [1]:
import pandas as pd

data = {
    "Order_ID": range(1001, 1051),

    "Customer": [
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja"
    ],

    "City": [
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai"
    ],

    "Category": [
        "Electronics", "Furniture", "Clothing", "Electronics", "Furniture",
        "Clothing", "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics", "Clothing"
    ],

    "Product": [
        "Laptop", "Chair", "T-Shirt", "Mobile", "Table",
        "Jeans", "Headphones", "Shoes", "Sofa", "Tablet",
        "Jacket", "Desk", "Laptop", "T-Shirt", "Chair",
        "Mobile", "Shoes", "Table", "Headphones", "Jeans",
        "Sofa", "Tablet", "Jacket", "Desk", "Laptop",
        "Shoes", "Chair", "Mobile", "T-Shirt", "Table",
        "Headphones", "Jeans", "Sofa", "Laptop", "Jacket",
        "Tablet", "Shoes", "Desk", "Mobile", "Chair",
        "T-Shirt", "Headphones", "Table", "Jeans", "Laptop",
        "Sofa", "Tablet", "Jacket", "Shoes", "Desk"
    ],

    "Quantity": [
        2, 1, 4, 2, 1,
        3, 2, 5, 1, 2,
        3, 2, 1, 4, 2,
        3, 5, 1, 2, 4,
        2, 3, 4, 1, 2,
        5, 2, 3, 4, 1,
        2, 3, 1, 4, 2,
        3, 5, 2, 1, 4,
        3, 2, 5, 1, 2,
        4, 3, 2, 5, 1
    ],

    "Sales": [
        1200, 800, 600, 1500, 900,
        700, 1100, 750, 1300, 1600,
        650, 1000, 1250, 700, 850,
        1400, 900, 1200, 1150, 800,
        1350, 1700, 650, 950, 1450,
        1000, 780, 1550, 720, 1100,
        1250, 850, 600, 1600, 900,
        950, 1400, 780, 1150, 1300,
        700, 1200, 1450, 820, 1050,
        1500, 900, 1350, 760, 1100
    ],

    "Profit": [
        200, 120, 150, 300, 180,
        140, 220, 160, 250, 320,
        130, 200, 250, 140, 170,
        280, 180, 240, 230, 160,
        270, 340, 130, 190, 290,
        200, 150, 310, 140, 220,
        250, 170, 120, 320, 180,
        190, 280, 150, 230, 260,
        140, 240, 290, 160, 210,
        300, 180, 270, 150, 220
    ],

    "Payment_Mode": [
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card"
    ],

    "Order_Status": [
        "Delivered", "Delivered", "Pending", "Delivered", "Cancelled",
        "Delivered", "Pending", "Delivered", "Cancelled", "Delivered",
        "Delivered", "Pending", "Delivered", "Cancelled", "Delivered",
        "Pending", "Delivered", "Delivered", "Cancelled", "Pending",
        "Delivered", "Delivered", "Cancelled", "Pending", "Delivered",
        "Delivered", "Pending", "Delivered", "Cancelled", "Delivered",
        "Pending", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Pending", "Cancelled", "Delivered", "Pending", "Delivered",
        "Delivered", "Cancelled", "Pending", "Delivered", "Delivered",
        "Pending", "Cancelled", "Delivered", "Pending", "Delivered"
    ]
}

df = pd.DataFrame(data)

print(df)

    Order_ID Customer    City     Category     Product  Quantity  Sales  \
0       1001     Amit   Delhi  Electronics      Laptop         2   1200
1       1002    Priya  Mumbai    Furniture       Chair         1    800
2       1003    Rahul  Jaipur     Clothing     T-Shirt         4    600
3       1004     Neha   Delhi  Electronics      Mobile         2   1500
4       1005    Vikas    Pune    Furniture       Table         1    900
5       1006    Sneha  Mumbai     Clothing       Jeans         3    700
6       1007    Rohit  Jaipur  Electronics  Headphones         2   1100
7       1008   Anjali   Delhi     Clothing       Shoes         5    750
8       1009    Karan    Pune    Furniture        Sofa         1   1300
9       1010    Pooja  Mumbai  Electronics      Tablet         2   1600
10      1011     Amit   Delhi     Clothing      Jacket         3    650
11      1012    Priya  Mumbai    Furniture        Desk         2   1000
12      1013    Rahul  Jaipur  Electronics      Laptop         1   1250
13      1014     Neha   Delhi     Clothing     T-Shirt         4    700
14      1015    Vikas    Pune    Furniture       Chair         2    850
15      1016    Sneha  Mumbai  Electronics      Mobile         3   1400
16      1017    Rohit  Jaipur     Clothing       Shoes         5    900
17      1018   Anjali   Delhi    Furniture       Table         1   1200
18      1019    Karan    Pune  Electronics  Headphones         2   1150
19      1020    Pooja  Mumbai     Clothing       Jeans         4    800
20      1021     Amit   Delhi    Furniture        Sofa         2   1350
21      1022    Priya  Mumbai  Electronics      Tablet         3   1700
22      1023    Rahul  Jaipur     Clothing      Jacket         4    650
23      1024     Neha   Delhi    Furniture        Desk         1    950
24      1025    Vikas    Pune  Electronics      Laptop         2   1450
25      1026    Sneha  Mumbai     Clothing       Shoes         5   1000
26      1027    Rohit  Jaipur    Furniture       Chair         2    780
27      1028   Anjali   Delhi  Electronics      Mobile         3   1550
28      1029    Karan    Pune     Clothing     T-Shirt         4    720
29      1030    Pooja  Mumbai    Furniture       Table         1   1100
30      1031     Amit   Delhi  Electronics  Headphones         2   1250
31      1032    Priya  Mumbai     Clothing       Jeans         3    850
32      1033    Rahul  Jaipur    Furniture        Sofa         1    600
33      1034     Neha   Delhi  Electronics      Laptop         4   1600
34      1035    Vikas    Pune     Clothing      Jacket         2    900
35      1036    Sneha  Mumbai    Furniture      Tablet         3    950
36      1037    Rohit  Jaipur  Electronics       Shoes         5   1400
37      1038   Anjali   Delhi     Clothing        Desk         2    780
38      1039    Karan    Pune    Furniture      Mobile         1   1150
39      1040    Pooja  Mumbai  Electronics       Chair         4   1300
40      1041     Amit   Delhi     Clothing     T-Shirt         3    700
41      1042    Priya  Mumbai    Furniture  Headphones         2   1200
42      1043    Rahul  Jaipur  Electronics       Table         5   1450
43      1044     Neha   Delhi     Clothing       Jeans         1    820
44      1045    Vikas    Pune    Furniture      Laptop         2   1050
45      1046    Sneha  Mumbai  Electronics        Sofa         4   1500
46      1047    Rohit  Jaipur     Clothing      Tablet         3    900
47      1048   Anjali   Delhi    Furniture      Jacket         2   1350
48      1049    Karan    Pune  Electronics       Shoes         5    760
49      1050    Pooja  Mumbai     Clothing        Desk         1   1100

    Profit Payment_Mode Order_Status
0      200          UPI    Delivered
1      120         Card    Delivered
2      150         Cash      Pending
3      300          UPI    Delivered
4      180         Card    Cancelled
5      140         Cash    Delivered
6      220          UPI      Pending
7      160         Card    Delivered
8      250         Cash    Cancelled
9      320          UPI    Delivered
10     130         Card    Delivered
11     200         Cash      Pending
12     250          UPI    Delivered
13     140         Card    Cancelled
14     170         Cash    Delivered
15     280          UPI      Pending
16     180         Card    Delivered
17     240         Cash    Delivered
18     230          UPI    Cancelled
19     160         Card      Pending
20     270         Cash    Delivered
21     340          UPI    Delivered
22     130         Card    Cancelled
23     190         Cash      Pending
24     290          UPI    Delivered
25     200         Card    Delivered
26     150         Cash      Pending
27     310          UPI    Delivered
28     140         Card    Cancelled
29     220         Cash    Delivered
30     250          UPI      Pending
31     170         Card    Delivered
32     120         Cash    Cancelled
33     320          UPI    Delivered
34     180         Card    Delivered
35     190         Cash      Pending
36     280          UPI    Cancelled
37     150         Card    Delivered
38     230         Cash      Pending
39     260          UPI    Delivered
40     140         Card    Delivered
41     240         Cash    Cancelled
42     290          UPI      Pending
43     160         Card    Delivered
44     210         Cash    Delivered
45     300          UPI      Pending
46     180         Card    Cancelled
47     270         Cash    Delivered
48     150          UPI      Pending
49     220         Card    Delivered

In [2]:
df.groupby("City")["Sales"].sum().reset_index()

     City  Sales
0   Delhi  16350
1  Jaipur   9630
2  Mumbai  17000
3    Pune  10230

In [4]:
df.groupby("City")["Sales"].sum()

City
Delhi     16350
Jaipur     9630
Mumbai    17000
Pune      10230
Name: Sales, dtype: int64

In [6]:
df.groupby("Category")["Sales"].mean()

Category
Clothing        795.294118
Electronics    1362.352941
Furniture      1033.125000
Name: Sales, dtype: float64

In [7]:
df.groupby("Category")["Sales"].mean().reset_index()

      Category        Sales
0     Clothing   795.294118
1  Electronics  1362.352941
2    Furniture  1033.125000

In [8]:
df.groupby("Category")["Profit"].sum().reset_index()

      Category  Profit
0     Clothing    2730
1  Electronics    4590
2    Furniture    3250

In [9]:
df.groupby("Product")["Quantity"].sum().reset_index()

       Product  Quantity
0        Chair         9
1         Desk         6
2   Headphones         8
3       Jacket        11
4        Jeans        11
5       Laptop        11
6       Mobile         9
7        Shoes        25
8         Sofa         8
9      T-Shirt        15
10       Table         8
11      Tablet        11

In [16]:
df.groupby("City")["Order_ID"].count().reset_index()

     City  Order_ID
0   Delhi        15
1  Jaipur        10
2  Mumbai        15
3    Pune        10

In [17]:
df.groupby("City")["Sales"].max().reset_index()

     City  Sales
0   Delhi   1600
1  Jaipur   1450
2  Mumbai   1700
3    Pune   1450

In [18]:
df.groupby("Category")["Profit"].min().reset_index()

      Category  Profit
0     Clothing     130
1  Electronics     150
2    Furniture     120

In [20]:
df.groupby("Payment_Mode")["Quantity"].mean().reset_index()

  Payment_Mode  Quantity
0         Card     3.000
1         Cash     1.875
2          UPI     3.000

In [22]:
df.groupby("Category")["Sales"].agg({"sum","mean","min","max"}).reset_index()

      Category         mean    sum   max  min
0     Clothing   795.294118  13520  1100  600
1  Electronics  1362.352941  23160  1700  760
2    Furniture  1033.125000  16530  1350  600

In [2]:
df.groupby("City")[["Sales","Profit"]].sum().reset_index()

     City  Sales  Profit
0   Delhi  16350    3230
1  Jaipur   9630    1950
2  Mumbai  17000    3360
3    Pune  10230    2030

In [3]:
df.groupby("Category")["Quantity"].agg({"sum","mean"}).reset_index()

      Category      mean  sum
0     Clothing  3.294118   56
1  Electronics  3.000000   51
2    Furniture  1.562500   25

In [4]:
df.groupby("City")[["Sales","Profit"]].agg({"sum","mean"}).reset_index()

     City        Sales             Profit
                  mean    sum        mean   sum
0   Delhi  1090.000000  16350  215.333333  3230
1  Jaipur   963.000000   9630  195.000000  1950
2  Mumbai  1133.333333  17000  224.000000  3360
3    Pune  1023.000000  10230  203.000000  2030

In [6]:
df.groupby(["Category","City"])["Sales"].sum()

Category     City
Clothing     Delhi     4400
             Jaipur    3050
             Mumbai    4450
             Pune      1620
Electronics  Delhi     7100
             Jaipur    5200
             Mumbai    7500
             Pune      3360
Furniture    Delhi     4850
             Jaipur    1380
             Mumbai    5050
             Pune      5250
Name: Sales, dtype: int64

In [7]:
df.groupby(["City","Payment_Mode"])["Profit"].sum().reset_index()

      City Payment_Mode  Profit
0    Delhi         Card     880
1    Delhi         Cash     970
2    Delhi          UPI    1380
3   Jaipur         Card     490
4   Jaipur         Cash     420
5   Jaipur          UPI    1040
6   Mumbai         Card     870
7   Mumbai         Cash     990
8   Mumbai          UPI    1500
9     Pune         Card     500
10    Pune         Cash     860
11    Pune          UPI     670

In [12]:
df.groupby(["Category","Payment_Mode"])["Sales"].mean().reset_index()

      Category Payment_Mode        Sales
0     Clothing         Card   814.666667
1     Clothing         Cash   650.000000
2  Electronics          UPI  1362.352941
3    Furniture         Card   850.000000
4    Furniture         Cash  1059.285714

In [13]:
df.groupby(["City","Category"])["Quantity"].sum().reset_index()

      City     Category  Quantity
0    Delhi     Clothing        18
1    Delhi  Electronics        13
2    Delhi    Furniture         6
3   Jaipur     Clothing        16
4   Jaipur  Electronics        13
5   Jaipur    Furniture         3
6   Mumbai     Clothing        16
7   Mumbai  Electronics        16
8   Mumbai    Furniture         9
9     Pune     Clothing         6
10    Pune  Electronics         9
11    Pune    Furniture         7

In [23]:
df.groupby("Payment_Mode").agg(
    Total_sale = ("Sales" , "sum"),
    Average_sale= ("Sales", "mean"),
    Total_profit = ("Profit","sum"),
    number_count = ("Order_Status","count")
)

              Total_sale  Average_sale  Total_profit  number_count
Payment_Mode
Card               13920    818.823529          2740            17
Cash               16130   1008.125000          3240            16
UPI                23160   1362.352941          4590            17

In [24]:
result = df.groupby("Payment_Mode").agg(
    Total_sale = ("Sales" , "sum"),
    Average_sale= ("Sales", "mean"),
    Total_profit = ("Profit","sum"),
    number_count = ("Order_Status","count")
)
result

              Total_sale  Average_sale  Total_profit  number_count
Payment_Mode
Card               13920    818.823529          2740            17
Cash               16130   1008.125000          3240            16
UPI                23160   1362.352941          4590            17