In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Employee": ["Aman", "Riya", "Neha", "Rahul", "Priya", "Karan", "Sneha", "Vikas"],
    "City": ["Jaipur", "Delhi", "Mumbai", "Jaipur", "Pune", "Delhi", "Mumbai", "Kota"],
    "Department": ["Sales", "HR", "IT", "Finance", "Sales", "IT", "HR", "Finance"],
    "Salary": [35000, 42000, 50000, 38000, 45000, 55000, 40000, 36000],
    "Experience": [2, 4, 5, 3, 4, 6, 3, 2],
    "Sales" : [85000 , 72000 , 125000 , 91000 , 115000 , 138000 , 79000 , 102000 ] ,
    "Rating": [3.8, 4.2, 4.7, 3.9, 4.5, 4.8, 4.1, 4.1]
})

df.index = ["E101", "E102", "E103", "E104", "E105", "E106", "E107", "E108"]

print(df)

     Employee    City Department  Salary  Experience   Sales  Rating
E101     Aman  Jaipur      Sales   35000           2   85000     3.8
E102     Riya   Delhi         HR   42000           4   72000     4.2
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9
E105    Priya    Pune      Sales   45000           4  115000     4.5
E106    Karan   Delhi         IT   55000           6  138000     4.8
E107    Sneha  Mumbai         HR   40000           3   79000     4.1
E108    Vikas    Kota    Finance   36000           2  102000     4.1

In [4]:
df.sort_values ( by = "Salary" , ascending = False )

     Employee    City Department  Salary  Experience   Sales  Rating
E106    Karan   Delhi         IT   55000           6  138000     4.8
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E105    Priya    Pune      Sales   45000           4  115000     4.5
E102     Riya   Delhi         HR   42000           4   72000     4.2
E107    Sneha  Mumbai         HR   40000           3   79000     4.1
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9
E108    Vikas    Kota    Finance   36000           2  102000     3.7
E101     Aman  Jaipur      Sales   35000           2   85000     3.8

In [5]:
df.sort_values (by = ["Department" ,"Salary" ] , ascending =[ True , False ] )

     Employee    City Department  Salary  Experience   Sales  Rating
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9
E108    Vikas    Kota    Finance   36000           2  102000     3.7
E102     Riya   Delhi         HR   42000           4   72000     4.2
E107    Sneha  Mumbai         HR   40000           3   79000     4.1
E106    Karan   Delhi         IT   55000           6  138000     4.8
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E105    Priya    Pune      Sales   45000           4  115000     4.5
E101     Aman  Jaipur      Sales   35000           2   85000     3.8

In [6]:
df.sort_values ( by = "Sales" , ascending = False ) .head (5)

     Employee    City Department  Salary  Experience   Sales  Rating
E106    Karan   Delhi         IT   55000           6  138000     4.8
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E105    Priya    Pune      Sales   45000           4  115000     4.5
E108    Vikas    Kota    Finance   36000           2  102000     3.7
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9

In [11]:
df.sort_values ( by = ["Rating" , "Experience" ]  , ascending = [ False , True ] )

     Employee    City Department  Salary  Experience   Sales  Rating
E106    Karan   Delhi         IT   55000           6  138000     4.8
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E105    Priya    Pune      Sales   45000           4  115000     4.5
E102     Riya   Delhi         HR   42000           4   72000     4.2
E108    Vikas    Kota    Finance   36000           2  102000     4.1
E107    Sneha  Mumbai         HR   40000           3   79000     4.1
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9
E101     Aman  Jaipur      Sales   35000           2   85000     3.8

In [14]:
df.sort_values ( by = ["City" , "Sales" ] , ascending = [ True , False ] ) [ [ "Employee" , "City" , "Sales" ]]

     Employee    City   Sales
E106    Karan   Delhi  138000
E102     Riya   Delhi   72000
E104    Rahul  Jaipur   91000
E101     Aman  Jaipur   85000
E108    Vikas    Kota  102000
E103     Neha  Mumbai  125000
E107    Sneha  Mumbai   79000
E105    Priya    Pune  115000

In [15]:
df.sort_values ( by = "Salary" , ascending = False ) .tail(4)

     Employee    City Department  Salary  Experience   Sales  Rating
E107    Sneha  Mumbai         HR   40000           3   79000     4.1
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9
E108    Vikas    Kota    Finance   36000           2  102000     4.1
E101     Aman  Jaipur      Sales   35000           2   85000     3.8

In [26]:
 df.loc ["E103" : "E108" ]

     Employee    City Department  Salary  Experience   Sales  Rating
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E104    Rahul  Jaipur    Finance   38000           3   91000     3.9
E105    Priya    Pune      Sales   45000           4  115000     4.5
E106    Karan   Delhi         IT   55000           6  138000     4.8
E107    Sneha  Mumbai         HR   40000           3   79000     4.1
E108    Vikas    Kota    Finance   36000           2  102000     4.1

In [32]:
df.loc [ df [ "Sales" ] > 100000 , [ "Employee" , "Department" , "Salary" ,"Sales" ] ]

     Employee Department  Salary   Sales
E103     Neha         IT   50000  125000
E105    Priya      Sales   45000  115000
E106    Karan         IT   55000  138000
E108    Vikas    Finance   36000  102000

In [39]:
df.loc [ df ["Department"] =="Finance" ,["Employee" , "City" , "Salary" ] ]

     Employee    City  Salary
E104    Rahul  Jaipur   38000
E108    Vikas    Kota   36000

In [9]:
df.loc [ df ["City"] .isin ( ["Jaipur" , "Delhi" ] ) & ( df ["Rating"] >= 4.0 ) ]

     Employee   City Department  Salary  Experience   Sales  Rating
E102     Riya  Delhi         HR   42000           4   72000     4.2
E106    Karan  Delhi         IT   55000           6  138000     4.8

In [14]:
df.loc [ ["E102" , "E105" , "E108" ] , [ "Employee" , "Department" , "Rating" ]]

     Employee Department  Rating
E102     Riya         HR     4.2
E105    Priya      Sales     4.5
E108    Vikas    Finance     4.1

In [7]:
df [ "Performance" ] = "Normal"
df.loc [ df ["Rating" ]  >= 4.5 , "Performance" ] = "High"
df

,Employee,City,Department,Salary,Experience,Sales,Rating,Performance
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,Normal
E102,Riya,Delhi,HR,42000,4,72000,4.2,Normal
E103,Neha,Mumbai,IT,50000,5,125000,4.7,High
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,Normal
E105,Priya,Pune,Sales,45000,4,115000,4.5,High
E106,Karan,Delhi,IT,55000,6,138000,4.8,High
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,Normal
E108,Vikas,Kota,Finance,36000,2,102000,4.1,Normal

In [21]:
df.iloc[2:7,:4]

     Employee    City Department  Salary
E103     Neha  Mumbai         IT   50000
E104    Rahul  Jaipur    Finance   38000
E105    Priya    Pune      Sales   45000
E106    Karan   Delhi         IT   55000
E107    Sneha  Mumbai         HR   40000

In [18]:
df.iloc [-5:] [ [ "Salary" , "Sales" , "Rating" ] ]

      Salary   Sales  Rating
E104   38000   91000     3.9
E105   45000  115000     4.5
E106   55000  138000     4.8
E107   40000   79000     4.1
E108   36000  102000     4.1

In [17]:
df.iloc [ ::2]

     Employee    City Department  Salary  Experience   Sales  Rating
E101     Aman  Jaipur      Sales   35000           2   85000     3.8
E103     Neha  Mumbai         IT   50000           5  125000     4.7
E105    Priya    Pune      Sales   45000           4  115000     4.5
E107    Sneha  Mumbai         HR   40000           3   79000     4.1

In [15]:
df.iloc [ [1 ,4, 7 ]] [[ "Employee" , "City" , "Sales" ]]

     Employee   City   Sales
E102     Riya  Delhi   72000
E105    Priya   Pune  115000
E108    Vikas   Kota  102000

In [22]:
df.iloc [:8 , -3:]

      Experience   Sales  Rating
E101           2   85000     3.8
E102           4   72000     4.2
E103           5  125000     4.7
E104           3   91000     3.9
E105           4  115000     4.5
E106           6  138000     4.8
E107           3   79000     4.1
E108           2  102000     4.1

In [29]:
df_sorted = df.sort_values ( by = "Sales" , ascending = False ) . reset_index ( drop = True )
df_sorted.iloc [ [ 1 , 4 , 7 ] ]

  Employee    City Department  Salary  Experience   Sales  Rating
1     Neha  Mumbai         IT   50000           5  125000     4.7
4    Rahul  Jaipur    Finance   38000           3   91000     3.9
7     Riya   Delhi         HR   42000           4   72000     4.2

In [30]:
df.sort_values ( by = "Sales" , ascending = False ) . reset_index ( drop = True ) .iloc [[1,4,7]]

  Employee    City Department  Salary  Experience   Sales  Rating
1     Neha  Mumbai         IT   50000           5  125000     4.7
4    Rahul  Jaipur    Finance   38000           3   91000     3.9
7     Riya   Delhi         HR   42000           4   72000     4.2

In [4]:
df ["Sales_Rank" ] = df [ "Sales" ] .rank (ascending = False , method = "min" ) .astype (int)
df

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,6
E102,Riya,Delhi,HR,42000,4,72000,4.2,8
E103,Neha,Mumbai,IT,50000,5,125000,4.7,2
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,5
E105,Priya,Pune,Sales,45000,4,115000,4.5,3
E106,Karan,Delhi,IT,55000,6,138000,4.8,1
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,7
E108,Vikas,Kota,Finance,36000,2,102000,4.1,4

In [5]:
df [ "Salary_Rank" ] = df [ "Salary" ] .rank ( ascending = False , method = "min" ) .astype(int)
df

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,6,8
E102,Riya,Delhi,HR,42000,4,72000,4.2,8,4
E103,Neha,Mumbai,IT,50000,5,125000,4.7,2,2
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,5,6
E105,Priya,Pune,Sales,45000,4,115000,4.5,3,3
E106,Karan,Delhi,IT,55000,6,138000,4.8,1,1
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,7,5
E108,Vikas,Kota,Finance,36000,2,102000,4.1,4,7

In [6]:
df [ "Rating_rank" ] = df ["Rating" ] .rank ( ascending = False , method = "min" ) .astype (int)
df

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,6,8,8
E102,Riya,Delhi,HR,42000,4,72000,4.2,8,4,4
E103,Neha,Mumbai,IT,50000,5,125000,4.7,2,2,2
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,5,6,7
E105,Priya,Pune,Sales,45000,4,115000,4.5,3,3,3
E106,Karan,Delhi,IT,55000,6,138000,4.8,1,1,1
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,7,5,5
E108,Vikas,Kota,Finance,36000,2,102000,4.1,4,7,5

In [10]:
df [ df ["Sales_Rank" ] <= 3 ]

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E103,Neha,Mumbai,IT,50000,5,125000,4.7,2,2,2
E105,Priya,Pune,Sales,45000,4,115000,4.5,3,3,3
E106,Karan,Delhi,IT,55000,6,138000,4.8,1,1,1

In [11]:
df [ df ["Sales_Rank"] .isin ( [1,2,3] ) ]

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E103,Neha,Mumbai,IT,50000,5,125000,4.7,2,2,2
E105,Priya,Pune,Sales,45000,4,115000,4.5,3,3,3
E106,Karan,Delhi,IT,55000,6,138000,4.8,1,1,1

In [19]:
df.query ( "Sales_Rank <= 3 " )

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E103,Neha,Mumbai,IT,50000,5,125000,4.7,2,2,2
E105,Priya,Pune,Sales,45000,4,115000,4.5,3,3,3
E106,Karan,Delhi,IT,55000,6,138000,4.8,1,1,1

In [26]:
df ["Sales_Rank"] = df ["Sales"] .rank ( ascending = False , method = "min" ) .astype(int)
df [ df ["Sales_Rank"] .between ( 5 , 8 ) ] .sort_values ("Sales_Rank")

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,5,6,7
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,6,8,8
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,7,5,5
E102,Riya,Delhi,HR,42000,4,72000,4.2,8,4,4

In [31]:
df [ df ["Sales_Rank"] .between ( 5, 8 ) ] .sort_values ( by = "Sales_Rank" , ascending = False )

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E102,Riya,Delhi,HR,42000,4,72000,4.2,8,4,4
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,7,5,5
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,6,8,8
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,5,6,7

In [32]:
df [ df ["Sales_Rank"] .between ( 5,8 ) ] .sort_values ( by = "Sales_Rank" ,ascending = True )

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,5,6,7
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,6,8,8
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,7,5,5
E102,Riya,Delhi,HR,42000,4,72000,4.2,8,4,4

In [34]:
df ["Sales_Rank"] = df ["Sales"] .rank ( ascending = True , method = "min" ) .astype(int) 
df ["Salary_Rank"] = df ["Salary"] .rank ( ascending = True ,method = "min" ) .astype(int)
df [ ( df ["Sales_Rank"] <= 5 ) | ( df ["Salary_Rank"] <= 5 ) ]

,Employee,City,Department,Salary,Experience,Sales,Rating,Sales_Rank,Salary_Rank,Rating_rank
E101,Aman,Jaipur,Sales,35000,2,85000,3.8,3,1,8
E102,Riya,Delhi,HR,42000,4,72000,4.2,1,5,4
E104,Rahul,Jaipur,Finance,38000,3,91000,3.9,4,3,7
E107,Sneha,Mumbai,HR,40000,3,79000,4.1,2,4,5
E108,Vikas,Kota,Finance,36000,2,102000,4.1,5,2,5