In [1]:
import numpy as np

In [2]:
import pandas as pd

In [21]:
df = pd.DataFrame({
    'Customer_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Customer_Name': [
        'aarav sharma',
        'RIYA   VERMA   ',
        'neha singh',
        ' Rahul Kumar    ',
        'Priya MEHTA ',
        'aman joshi',
        'Karan Sharma',
        ' sneha gupta '
    ],
    'City': [
        'jaipur', 'Delhi ', ' MUMBAI', 'Jaipur',
        'delhi', 'Mumbai ', 'JODHPUR', ' jaipur '
    ],
    'Product': [
        'Smartphone',
        'Laptop',
        'Phone Case',
        'Shoes',
        'Smart Watch',
        'Tablet',
        'Speaker',
        'Mobile Phone'
    ],
    'Email': [
        'aarav@gmail.com',
        'riya@yahoo.com',
        'neha@gmail.com',
        'rahul@outlook.com',
        'priya@gmail.com',
        'aman@yahoo.com',
        'karan@gmail.com',
        'sneha@outlook.com'
    ]
})
df

   Customer_ID     Customer_Name      City       Product              Email
0          101      aarav sharma    jaipur    Smartphone    aarav@gmail.com
1          102   RIYA   VERMA       Delhi         Laptop     riya@yahoo.com
2          103        neha singh    MUMBAI    Phone Case     neha@gmail.com
3          104   Rahul Kumar        Jaipur         Shoes  rahul@outlook.com
4          105      Priya MEHTA      delhi   Smart Watch    priya@gmail.com
5          106        aman joshi   Mumbai         Tablet     aman@yahoo.com
6          107      Karan Sharma   JODHPUR       Speaker    karan@gmail.com
7          108      sneha gupta    jaipur   Mobile Phone  sneha@outlook.com

In [6]:
df ["Customer_Name"] = df ["Customer_Name"] .str.upper() 
df

   Customer_ID     Customer_Name      City       Product              Email
0          101      AARAV SHARMA    jaipur    Smartphone    aarav@gmail.com
1          102   RIYA   VERMA       Delhi         Laptop     riya@yahoo.com
2          103        NEHA SINGH    MUMBAI    Phone Case     neha@gmail.com
3          104   RAHUL KUMAR        Jaipur         Shoes  rahul@outlook.com
4          105      PRIYA MEHTA      delhi   Smart Watch    priya@gmail.com
5          106        AMAN JOSHI   Mumbai         Tablet     aman@yahoo.com
6          107      KARAN SHARMA   JODHPUR       Speaker    karan@gmail.com
7          108      SNEHA GUPTA    jaipur   Mobile Phone  sneha@outlook.com

In [7]:
df ["Customer_Name"] = df ["Customer_Name"] .str.title() 
df

   Customer_ID     Customer_Name      City       Product              Email
0          101      Aarav Sharma    jaipur    Smartphone    aarav@gmail.com
1          102   Riya   Verma       Delhi         Laptop     riya@yahoo.com
2          103        Neha Singh    MUMBAI    Phone Case     neha@gmail.com
3          104   Rahul Kumar        Jaipur         Shoes  rahul@outlook.com
4          105      Priya Mehta      delhi   Smart Watch    priya@gmail.com
5          106        Aman Joshi   Mumbai         Tablet     aman@yahoo.com
6          107      Karan Sharma   JODHPUR       Speaker    karan@gmail.com
7          108      Sneha Gupta    jaipur   Mobile Phone  sneha@outlook.com

In [8]:
df ["Customer_Name"] = df ["Customer_Name"] .str.strip() 
df

   Customer_ID Customer_Name      City       Product              Email
0          101  Aarav Sharma    jaipur    Smartphone    aarav@gmail.com
1          102  Riya   Verma    Delhi         Laptop     riya@yahoo.com
2          103    Neha Singh    MUMBAI    Phone Case     neha@gmail.com
3          104   Rahul Kumar    Jaipur         Shoes  rahul@outlook.com
4          105   Priya Mehta     delhi   Smart Watch    priya@gmail.com
5          106    Aman Joshi   Mumbai         Tablet     aman@yahoo.com
6          107  Karan Sharma   JODHPUR       Speaker    karan@gmail.com
7          108   Sneha Gupta   jaipur   Mobile Phone  sneha@outlook.com

In [9]:
df ["Customer_Name"] = df ["Customer_Name"] .str.len() 
df

   Customer_ID  Customer_Name      City       Product              Email
0          101             12    jaipur    Smartphone    aarav@gmail.com
1          102             12    Delhi         Laptop     riya@yahoo.com
2          103             10    MUMBAI    Phone Case     neha@gmail.com
3          104             11    Jaipur         Shoes  rahul@outlook.com
4          105             11     delhi   Smart Watch    priya@gmail.com
5          106             10   Mumbai         Tablet     aman@yahoo.com
6          107             12   JODHPUR       Speaker    karan@gmail.com
7          108             11   jaipur   Mobile Phone  sneha@outlook.com

In [15]:
df[df ["Product"].str.contains("Phone" , case = False , na = False )]

   Customer_ID  Customer_Name      City       Product              Email
0          101   aarav sharma    jaipur    Smartphone    aarav@gmail.com
2          103     neha singh    MUMBAI    Phone Case     neha@gmail.com
7          108   sneha gupta    jaipur   Mobile Phone  sneha@outlook.com

In [22]:
df [ df["Customer_Name"].str.startswith("a" , na = False ) ]

   Customer_ID Customer_Name     City     Product            Email
0          101  aarav sharma   jaipur  Smartphone  aarav@gmail.com
5          106    aman joshi  Mumbai       Tablet   aman@yahoo.com

In [25]:
df [ df["Customer_Name"].str.endswith("a" , na = False ) ]

   Customer_ID Customer_Name     City     Product            Email
0          101  aarav sharma   jaipur  Smartphone  aarav@gmail.com
6          107  Karan Sharma  JODHPUR     Speaker  karan@gmail.com

In [32]:
df[df["Product"].str.endswith("e" , na = False ) ]

   Customer_ID  Customer_Name      City       Product              Email
0          101   aarav sharma    jaipur    Smartphone    aarav@gmail.com
2          103     neha singh    MUMBAI    Phone Case     neha@gmail.com
7          108   sneha gupta    jaipur   Mobile Phone  sneha@outlook.com

In [30]:
df["Product"].str.replace("Smartphone" , "Smart Phone" )

0     Smart Phone
1          Laptop
2      Phone Case
3           Shoes
4     Smart Watch
5          Tablet
6         Speaker
7    Mobile Phone
Name: Product, dtype: object

In [33]:
df ["Customer_Name"] .str[0]

0    a
1    R
2    n
3
4    P
5    a
6    K
7
Name: Customer_Name, dtype: object

In [36]:
df ["Customer_Name"] .str.split().str[-1]

0    sharma
1     VERMA
2     singh
3     Kumar
4     MEHTA
5     joshi
6    Sharma
7     gupta
Name: Customer_Name, dtype: object

In [37]:
df ["Customer_Name"] .str.split().str[0]

0    aarav
1     RIYA
2     neha
3    Rahul
4    Priya
5     aman
6    Karan
7    sneha
Name: Customer_Name, dtype: object

In [40]:
df["Email"].str.split("@").str[0]

0    aarav
1     riya
2     neha
3    rahul
4    priya
5     aman
6    karan
7    sneha
Name: Email, dtype: object

In [41]:
df["Email"].str.split("@").str[1]

0      gmail.com
1      yahoo.com
2      gmail.com
3    outlook.com
4      gmail.com
5      yahoo.com
6      gmail.com
7    outlook.com
Name: Email, dtype: object

In [43]:
df[df["Email"].str.endswith("gmail.com" , na = False ) ]

   Customer_ID Customer_Name     City      Product            Email
0          101  aarav sharma   jaipur   Smartphone  aarav@gmail.com
2          103    neha singh   MUMBAI   Phone Case   neha@gmail.com
4          105  Priya MEHTA     delhi  Smart Watch  priya@gmail.com
6          107  Karan Sharma  JODHPUR      Speaker  karan@gmail.com

In [46]:
 df["Customer_Name"] .str.strip().str.title()

0    Aarav Sharma
1    Riya   Verma
2      Neha Singh
3     Rahul Kumar
4     Priya Mehta
5      Aman Joshi
6    Karan Sharma
7     Sneha Gupta
Name: Customer_Name, dtype: object

In [50]:
df[df ["Customer_Name"] .str.contains("Sharma" , case = False ) ]

   Customer_ID Customer_Name     City     Product            Email
0          101  aarav sharma   jaipur  Smartphone  aarav@gmail.com
6          107  Karan Sharma  JODHPUR     Speaker  karan@gmail.com

In [53]:
df[df["Product"] .str.contains("phone|smart" , case = False ) ]

   Customer_ID  Customer_Name      City       Product              Email
0          101   aarav sharma    jaipur    Smartphone    aarav@gmail.com
2          103     neha singh    MUMBAI    Phone Case     neha@gmail.com
4          105   Priya MEHTA      delhi   Smart Watch    priya@gmail.com
7          108   sneha gupta    jaipur   Mobile Phone  sneha@outlook.com

In [54]:
df["Customer_Name"].str.split().str.len()

0    2
1    2
2    2
3    2
4    2
5    2
6    2
7    2
Name: Customer_Name, dtype: int64

In [64]:
df[["First_Name","Last_Name"]] = df["Customer_Name"].str.strip().str.split(" ",n=1 ,expand=True ) 
df

,Customer_ID,Customer_Name,City,Product,Email,First_Name,Last_Name
0,101,aarav sharma,jaipur,Smartphone,aarav@gmail.com,aarav,sharma
1,102,RIYA VERMA,Delhi,Laptop,riya@yahoo.com,RIYA,VERMA
2,103,neha singh,MUMBAI,Phone Case,neha@gmail.com,neha,singh
3,104,Rahul Kumar,Jaipur,Shoes,rahul@outlook.com,Rahul,Kumar
4,105,Priya MEHTA,delhi,Smart Watch,priya@gmail.com,Priya,MEHTA
5,106,aman joshi,Mumbai,Tablet,aman@yahoo.com,aman,joshi
6,107,Karan Sharma,JODHPUR,Speaker,karan@gmail.com,Karan,Sharma
7,108,sneha gupta,jaipur,Mobile Phone,sneha@outlook.com,sneha,gupta