In [2]:
import pandas as pd

In [3]:
import numpy as np

In [7]:
sales_jan = pd.DataFrame({
    'Order_ID': [101, 102, 103],
    'Customer': ['Amit', 'Priya', 'Rahul'],
    'Sales': [5000, 7000, 6000]
})
sales_jan

   Order_ID Customer  Sales
0       101     Amit   5000
1       102    Priya   7000
2       103    Rahul   6000

In [8]:
sales_feb = pd.DataFrame({
    'Order_ID': [104, 105, 106],
    'Customer': ['Neha', 'Vikas', 'Sneha'],
    'Sales': [8000, 4000, 9000]
})

sales_feb

   Order_ID Customer  Sales
0       104     Neha   8000
1       105    Vikas   4000
2       106    Sneha   9000

In [9]:
sales_mar = pd.DataFrame({
    'Order_ID': [107, 108, 109],
    'Customer': ['Karan', 'Riya', 'Mohit'],
    'Sales': [5500, 6500, 7500],
    'City': ['Delhi', 'Mumbai', 'Jaipur']
})

sales_mar

   Order_ID Customer  Sales    City
0       107    Karan   5500   Delhi
1       108     Riya   6500  Mumbai
2       109    Mohit   7500  Jaipur

In [17]:
df_sales = pd.concat([sales_jan,sales_feb],axis = 0)
print(df_sales)

   Order_ID Customer  Sales
0       101     Amit   5000
1       102    Priya   7000
2       103    Rahul   6000
0       104     Neha   8000
1       105    Vikas   4000
2       106    Sneha   9000

In [14]:
df_sales = pd.concat([sales_jan,sales_feb],ignore_index = True)
print(df_sales)

   Order_ID Customer  Sales
0       101     Amit   5000
1       102    Priya   7000
2       103    Rahul   6000
3       104     Neha   8000
4       105    Vikas   4000
5       106    Sneha   9000

In [16]:
df_sales = pd.concat([sales_jan,sales_feb,sales_mar],axis = 0)
print(df_sales)

   Order_ID Customer  Sales    City
0       101     Amit   5000     NaN
1       102    Priya   7000     NaN
2       103    Rahul   6000     NaN
0       104     Neha   8000     NaN
1       105    Vikas   4000     NaN
2       106    Sneha   9000     NaN
0       107    Karan   5500   Delhi
1       108     Riya   6500  Mumbai
2       109    Mohit   7500  Jaipur

In [18]:
df_sales = pd.concat([sales_jan,sales_feb],axis = 1)
print(df_sales)

   Order_ID Customer  Sales  Order_ID Customer  Sales
0       101     Amit   5000       104     Neha   8000
1       102    Priya   7000       105    Vikas   4000
2       103    Rahul   6000       106    Sneha   9000

In [19]:
pd.concat([sales_jan[["Customer"]], sales_feb[["Customer"]]],axis = 1)

  Customer Customer
0     Amit     Neha
1    Priya    Vikas
2    Rahul    Sneha

In [20]:
pd.concat([sales_jan[["Customer"]], sales_feb[["Customer"]]],axis = 1,keys = ["jan","feb"])

       jan      feb
  Customer Customer
0     Amit     Neha
1    Priya    Vikas
2    Rahul    Sneha

In [24]:
df_sales = pd.concat([sales_jan,sales_feb,sales_mar])["Sales"].sum()
print(df_sales)

58500