In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Student_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        111, 112, 113, 114, 115
    ],

    "Student_Name": [
        "Aarav", "Riya", "Neha", "Rahul", "Priya",
        "Aman", "Kavya", "Rohit", "Simran", "Vikas",
        "Anjali", "Karan", "Meera", "Arjun", "Nisha"
    ],

    "DOB": [
        "2006-01-15", "2005-03-20", "2006-06-10",
        "2005-09-25", "2006-02-12", "2005-11-30",
        "2006-04-18", "2005-07-22", "2006-08-05",
        "2005-12-17", "2006-10-28", "2005-05-11",
        "2006-12-20", "2005-01-08", "2006-07-14"
    ],

    "Admission_Date": [
        "2024-07-10", "2024-07-12", "2024-07-15",
        "2024-07-18", "2024-07-20", "2024-07-22",
        "2024-07-25", "2024-07-28", "2024-08-01",
        "2024-08-03", "2024-08-05", "2024-08-08",
        "2024-08-10", "2024-08-12", "2024-08-15"
    ],

    "Course": [
        "Python", "SQL", "Python", "Power BI", "SQL",
        "Python", "Excel", "Power BI", "Python", "SQL",
        "Excel", "Python", "Power BI", "SQL", "Python"
    ],

    "Marks": [
        78, 85, 92, 67, 74,
        88, 95, 61, 83, 72,
        90, 56, 81, 69, 97
    ],

    "Attendance": [
        92, 88, 95, 76, 84,
        91, 98, 72, 89, 81,
        94, 68, 87, 79, 96
    ],

    "Study_Hours": [
        3, 4, 5, 2, 3,
        4, 6, 2, 4, 3,
        5, 2, 4, 3, 6
    ],

    "Fees_Paid": [
        15000, 18000, 15000, 20000, 18000,
        15000, 12000, 20000, 15000, 18000,
        12000, 15000, 20000, 18000, 15000
    ]
})

print(df)

    Student_ID Student_Name         DOB Admission_Date    Course  Marks  \
0          101        Aarav  2006-01-15     2024-07-10    Python     78
1          102         Riya  2005-03-20     2024-07-12       SQL     85
2          103         Neha  2006-06-10     2024-07-15    Python     92
3          104        Rahul  2005-09-25     2024-07-18  Power BI     67
4          105        Priya  2006-02-12     2024-07-20       SQL     74
5          106         Aman  2005-11-30     2024-07-22    Python     88
6          107        Kavya  2006-04-18     2024-07-25     Excel     95
7          108        Rohit  2005-07-22     2024-07-28  Power BI     61
8          109       Simran  2006-08-05     2024-08-01    Python     83
9          110        Vikas  2005-12-17     2024-08-03       SQL     72
10         111       Anjali  2006-10-28     2024-08-05     Excel     90
11         112        Karan  2005-05-11     2024-08-08    Python     56
12         113        Meera  2006-12-20     2024-08-10  Power BI     81
13         114        Arjun  2005-01-08     2024-08-12       SQL     69
14         115        Nisha  2006-07-14     2024-08-15    Python     97

    Attendance  Study_Hours  Fees_Paid
0           92            3      15000
1           88            4      18000
2           95            5      15000
3           76            2      20000
4           84            3      18000
5           91            4      15000
6           98            6      12000
7           72            2      20000
8           89            4      15000
9           81            3      18000
10          94            5      12000
11          68            2      15000
12          87            4      20000
13          79            3      18000
14          96            6      15000

In [4]:
unique_value_course = df["Course"].unique()
print(unique_value_course)

['Python' 'SQL' 'Power BI' 'Excel']

In [5]:
unique_value_course = df["Course"].nunique()
print(unique_value_course)

4

In [9]:
students_enrolled_count = df['Course'].value_counts()
print(students_enrolled_count)

Course
Python      6
SQL         4
Power BI    3
Excel       2
Name: count, dtype: int64

In [12]:
student_counts = df['Student_ID'].count()
print(student_counts)

15

In [13]:
Top_3_courses = df['Course'].value_counts().head(3)
print(Top_3_courses)

Course
Python      6
SQL         4
Power BI    3
Name: count, dtype: int64

In [15]:
percentage_distribution = df['Course'].value_counts(normalize = True)*100
print(percentage_distribution)

Course
Python      40.000000
SQL         26.666667
Power BI    20.000000
Excel       13.333333
Name: proportion, dtype: float64

In [16]:
frequency = df['Study_Hours'].value_counts()
print(frequency)

Study_Hours
3    4
4    4
2    3
5    2
6    2
Name: count, dtype: int64

In [17]:
unique_number = df["Marks"].unique()
print(unique_number)

[78 85 92 67 74 88 95 61 83 72 90 56 81 69 97]

In [18]:
df["Marks"].unique()

array([78, 85, 92, 67, 74, 88, 95, 61, 83, 72, 90, 56, 81, 69, 97])

In [19]:
df["Marks"].nunique()

15

In [21]:
df["Students_Marks"] = df["Marks"].rename()
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid,Students_Marks
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000,78
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000,85
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000,92
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000,67
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000,74
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000,88
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000,95
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000,61
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000,83
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000,72
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000,90
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000,56
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000,81
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000,69
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000,97

In [25]:
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [27]:
df.rename(columns={"Marks":"Students_Marks"}, inplace = True)

In [28]:
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Students_Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [29]:
df.rename(columns= {"Study_Hours":"Daily_Study_Hours","Fees_Paid":"Course_Fees"},inplace = True)

In [30]:
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Students_Marks,Attendance,Daily_Study_Hours,Course_Fees
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [31]:
df = df.drop(columns= ["Attendance"])

In [32]:
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Students_Marks,Daily_Study_Hours,Course_Fees
0,101,Aarav,2006-01-15,2024-07-10,Python,78,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,6,15000

In [33]:
df.drop(columns= ["DOB","Admission_Date"])

,Student_ID,Student_Name,Course,Students_Marks,Daily_Study_Hours,Course_Fees
0,101,Aarav,Python,78,3,15000
1,102,Riya,SQL,85,4,18000
2,103,Neha,Python,92,5,15000
3,104,Rahul,Power BI,67,2,20000
4,105,Priya,SQL,74,3,18000
5,106,Aman,Python,88,4,15000
6,107,Kavya,Excel,95,6,12000
7,108,Rohit,Power BI,61,2,20000
8,109,Simran,Python,83,4,15000
9,110,Vikas,SQL,72,3,18000
10,111,Anjali,Excel,90,5,12000
11,112,Karan,Python,56,2,15000
12,113,Meera,Power BI,81,4,20000
13,114,Arjun,SQL,69,3,18000
14,115,Nisha,Python,97,6,15000

In [34]:
df.drop([0,1,2],inplace = True)

In [35]:
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Students_Marks,Daily_Study_Hours,Course_Fees
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,6,15000

In [36]:
df.reset_index(drop=True , inplace = True)

In [37]:
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Students_Marks,Daily_Study_Hours,Course_Fees
0,104,Rahul,2005-09-25,2024-07-18,Power BI,67,2,20000
1,105,Priya,2006-02-12,2024-07-20,SQL,74,3,18000
2,106,Aman,2005-11-30,2024-07-22,Python,88,4,15000
3,107,Kavya,2006-04-18,2024-07-25,Excel,95,6,12000
4,108,Rohit,2005-07-22,2024-07-28,Power BI,61,2,20000
5,109,Simran,2006-08-05,2024-08-01,Python,83,4,15000
6,110,Vikas,2005-12-17,2024-08-03,SQL,72,3,18000
7,111,Anjali,2006-10-28,2024-08-05,Excel,90,5,12000
8,112,Karan,2005-05-11,2024-08-08,Python,56,2,15000
9,113,Meera,2006-12-20,2024-08-10,Power BI,81,4,20000
10,114,Arjun,2005-01-08,2024-08-12,SQL,69,3,18000
11,115,Nisha,2006-07-14,2024-08-15,Python,97,6,15000

In [5]:
df.insert(loc = 2,column="Students_type",value = "Regular")

In [6]:
df

,Student_ID,Student_Name,Students_type,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,Regular,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,Regular,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,Regular,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,Regular,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,Regular,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,Regular,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,Regular,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,108,Rohit,Regular,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,109,Simran,Regular,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,Regular,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,111,Anjali,Regular,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,Regular,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,Regular,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,Regular,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,Regular,2006-07-14,2024-08-15,Python,97,96,6,15000

In [8]:
df.insert (loc = 0,column = "Country" , value = "India")

In [9]:
df

,Country,Student_ID,Student_Name,Students_type,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,India,101,Aarav,Regular,2006-01-15,2024-07-10,Python,78,92,3,15000
1,India,102,Riya,Regular,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,India,103,Neha,Regular,2006-06-10,2024-07-15,Python,92,95,5,15000
3,India,104,Rahul,Regular,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,India,105,Priya,Regular,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,India,106,Aman,Regular,2005-11-30,2024-07-22,Python,88,91,4,15000
6,India,107,Kavya,Regular,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,India,108,Rohit,Regular,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,India,109,Simran,Regular,2006-08-05,2024-08-01,Python,83,89,4,15000
9,India,110,Vikas,Regular,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,India,111,Anjali,Regular,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,India,112,Karan,Regular,2005-05-11,2024-08-08,Python,56,68,2,15000
12,India,113,Meera,Regular,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,India,114,Arjun,Regular,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,India,115,Nisha,Regular,2006-07-14,2024-08-15,Python,97,96,6,15000

In [12]:
df["Performance"] = pd.cut(df["Marks"],
                           bins = [ -1, 60, 70, 80, 90,100],
                           labels = ["Poor" , "Average" ,"Good" ,"Very good", "Excellent"]
                          )
df

,Country,Student_ID,Student_Name,Students_type,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid,Performance
0,India,101,Aarav,Regular,2006-01-15,2024-07-10,Python,78,92,3,15000,Good
1,India,102,Riya,Regular,2005-03-20,2024-07-12,SQL,85,88,4,18000,Very good
2,India,103,Neha,Regular,2006-06-10,2024-07-15,Python,92,95,5,15000,Excellent
3,India,104,Rahul,Regular,2005-09-25,2024-07-18,Power BI,67,76,2,20000,Average
4,India,105,Priya,Regular,2006-02-12,2024-07-20,SQL,74,84,3,18000,Good
5,India,106,Aman,Regular,2005-11-30,2024-07-22,Python,88,91,4,15000,Very good
6,India,107,Kavya,Regular,2006-04-18,2024-07-25,Excel,95,98,6,12000,Excellent
7,India,108,Rohit,Regular,2005-07-22,2024-07-28,Power BI,61,72,2,20000,Average
8,India,109,Simran,Regular,2006-08-05,2024-08-01,Python,83,89,4,15000,Very good
9,India,110,Vikas,Regular,2005-12-17,2024-08-03,SQL,72,81,3,18000,Good
10,India,111,Anjali,Regular,2006-10-28,2024-08-05,Excel,90,94,5,12000,Very good
11,India,112,Karan,Regular,2005-05-11,2024-08-08,Python,56,68,2,15000,Poor
12,India,113,Meera,Regular,2006-12-20,2024-08-10,Power BI,81,87,4,20000,Very good
13,India,114,Arjun,Regular,2005-01-08,2024-08-12,SQL,69,79,3,18000,Average
14,India,115,Nisha,Regular,2006-07-14,2024-08-15,Python,97,96,6,15000,Excellent

In [13]:
df["Attendance_Group"] = pd.cut(df["Attendance"],
                                bins = [-1,74,84,94,100],
                                labels = ["low" , "moderate" ,"good" , "Excellent"]
                               )
df

,Country,Student_ID,Student_Name,Students_type,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid,Performance,Attendance_Group
0,India,101,Aarav,Regular,2006-01-15,2024-07-10,Python,78,92,3,15000,Good,good
1,India,102,Riya,Regular,2005-03-20,2024-07-12,SQL,85,88,4,18000,Very good,good
2,India,103,Neha,Regular,2006-06-10,2024-07-15,Python,92,95,5,15000,Excellent,Excellent
3,India,104,Rahul,Regular,2005-09-25,2024-07-18,Power BI,67,76,2,20000,Average,moderate
4,India,105,Priya,Regular,2006-02-12,2024-07-20,SQL,74,84,3,18000,Good,moderate
5,India,106,Aman,Regular,2005-11-30,2024-07-22,Python,88,91,4,15000,Very good,good
6,India,107,Kavya,Regular,2006-04-18,2024-07-25,Excel,95,98,6,12000,Excellent,Excellent
7,India,108,Rohit,Regular,2005-07-22,2024-07-28,Power BI,61,72,2,20000,Average,low
8,India,109,Simran,Regular,2006-08-05,2024-08-01,Python,83,89,4,15000,Very good,good
9,India,110,Vikas,Regular,2005-12-17,2024-08-03,SQL,72,81,3,18000,Good,moderate
10,India,111,Anjali,Regular,2006-10-28,2024-08-05,Excel,90,94,5,12000,Very good,good
11,India,112,Karan,Regular,2005-05-11,2024-08-08,Python,56,68,2,15000,Poor,low
12,India,113,Meera,Regular,2006-12-20,2024-08-10,Power BI,81,87,4,20000,Very good,good
13,India,114,Arjun,Regular,2005-01-08,2024-08-12,SQL,69,79,3,18000,Average,moderate
14,India,115,Nisha,Regular,2006-07-14,2024-08-15,Python,97,96,6,15000,Excellent,Excellent

In [14]:
df["Study_Group"] = pd.cut(df["Study_Hours"],
                           bins=[-1,2,4,6],
                           labels=["low","moderate","high"]
                          )
df

,Country,Student_ID,Student_Name,Students_type,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid,Performance,Attendance_Group,Study_Group
0,India,101,Aarav,Regular,2006-01-15,2024-07-10,Python,78,92,3,15000,Good,good,moderate
1,India,102,Riya,Regular,2005-03-20,2024-07-12,SQL,85,88,4,18000,Very good,good,moderate
2,India,103,Neha,Regular,2006-06-10,2024-07-15,Python,92,95,5,15000,Excellent,Excellent,high
3,India,104,Rahul,Regular,2005-09-25,2024-07-18,Power BI,67,76,2,20000,Average,moderate,low
4,India,105,Priya,Regular,2006-02-12,2024-07-20,SQL,74,84,3,18000,Good,moderate,moderate
5,India,106,Aman,Regular,2005-11-30,2024-07-22,Python,88,91,4,15000,Very good,good,moderate
6,India,107,Kavya,Regular,2006-04-18,2024-07-25,Excel,95,98,6,12000,Excellent,Excellent,high
7,India,108,Rohit,Regular,2005-07-22,2024-07-28,Power BI,61,72,2,20000,Average,low,low
8,India,109,Simran,Regular,2006-08-05,2024-08-01,Python,83,89,4,15000,Very good,good,moderate
9,India,110,Vikas,Regular,2005-12-17,2024-08-03,SQL,72,81,3,18000,Good,moderate,moderate
10,India,111,Anjali,Regular,2006-10-28,2024-08-05,Excel,90,94,5,12000,Very good,good,high
11,India,112,Karan,Regular,2005-05-11,2024-08-08,Python,56,68,2,15000,Poor,low,low
12,India,113,Meera,Regular,2006-12-20,2024-08-10,Power BI,81,87,4,20000,Very good,good,moderate
13,India,114,Arjun,Regular,2005-01-08,2024-08-12,SQL,69,79,3,18000,Average,moderate,moderate
14,India,115,Nisha,Regular,2006-07-14,2024-08-15,Python,97,96,6,15000,Excellent,Excellent,high

In [16]:
df["Performance"].value_counts()

Performance
Very good    5
Average      3
Good         3
Excellent    3
Poor         1
Name: count, dtype: int64

In [17]:
df["Performance"].value_counts(sort = False)

Performance
Poor         1
Average      3
Good         3
Very good    5
Excellent    3
Name: count, dtype: int64

In [19]:
df["Performance"].value_counts(normalize = True) *100

Performance
Very good    33.333333
Average      20.000000
Good         20.000000
Excellent    20.000000
Poor          6.666667
Name: proportion, dtype: float64

In [20]:
new_order = [ 'Student_ID', 'Student_Name', 'Course', 'Marks', 'Attendance','Study_Hours', 'Fees_Paid', 'DOB', 'Admission_Date']
df=df[new_order]
df

,Student_ID,Student_Name,Course,Marks,Attendance,Study_Hours,Fees_Paid,DOB,Admission_Date
0,101,Aarav,Python,78,92,3,15000,2006-01-15,2024-07-10
1,102,Riya,SQL,85,88,4,18000,2005-03-20,2024-07-12
2,103,Neha,Python,92,95,5,15000,2006-06-10,2024-07-15
3,104,Rahul,Power BI,67,76,2,20000,2005-09-25,2024-07-18
4,105,Priya,SQL,74,84,3,18000,2006-02-12,2024-07-20
5,106,Aman,Python,88,91,4,15000,2005-11-30,2024-07-22
6,107,Kavya,Excel,95,98,6,12000,2006-04-18,2024-07-25
7,108,Rohit,Power BI,61,72,2,20000,2005-07-22,2024-07-28
8,109,Simran,Python,83,89,4,15000,2006-08-05,2024-08-01
9,110,Vikas,SQL,72,81,3,18000,2005-12-17,2024-08-03
10,111,Anjali,Excel,90,94,5,12000,2006-10-28,2024-08-05
11,112,Karan,Python,56,68,2,15000,2005-05-11,2024-08-08
12,113,Meera,Power BI,81,87,4,20000,2006-12-20,2024-08-10
13,114,Arjun,SQL,69,79,3,18000,2005-01-08,2024-08-12
14,115,Nisha,Python,97,96,6,15000,2006-07-14,2024-08-15

In [23]:
new_df = df[["Student_ID", "Student_Name", "Course", "Marks", "Fees_Paid"]]
new_df

    Student_ID Student_Name    Course  Marks  Fees_Paid
0          101        Aarav    Python     78      15000
1          102         Riya       SQL     85      18000
2          103         Neha    Python     92      15000
3          104        Rahul  Power BI     67      20000
4          105        Priya       SQL     74      18000
5          106         Aman    Python     88      15000
6          107        Kavya     Excel     95      12000
7          108        Rohit  Power BI     61      20000
8          109       Simran    Python     83      15000
9          110        Vikas       SQL     72      18000
10         111       Anjali     Excel     90      12000
11         112        Karan    Python     56      15000
12         113        Meera  Power BI     81      20000
13         114        Arjun       SQL     69      18000
14         115        Nisha    Python     97      15000

In [27]:
df["Course"].mode()[0]

'Python'

In [26]:
df["Course"].unique()
df["Course"].value_counts(normalize = True) * 100

Course
Python      40.000000
SQL         26.666667
Power BI    20.000000
Excel       13.333333
Name: proportion, dtype: float64