In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = {
    'Order_ID': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210,
                 211, 212, 213, 214, 215],

    'Region': ['North', 'South', 'East', 'West', 'North',
               'South', 'East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South', 'East'],

    'Product': ['Laptop', 'Mobile', 'Tablet', 'Laptop', 'Mobile',
                'Tablet', 'Laptop', 'Mobile', 'Tablet', 'Laptop',
                'Mobile', 'Tablet', 'Laptop', 'Mobile', 'Tablet'],

    'Salesperson': ['Raj', 'Priya', 'Aman', 'Neha', 'Raj',
                    'Priya', 'Aman', 'Neha', 'Raj', 'Priya',
                    'Aman', 'Neha', 'Raj', 'Priya', 'Aman'],

    'Sales': [55000, 30000, 22000, 48000, 35000,
              25000, 60000, 28000, 24000, 52000,
              33000, 27000, 65000, 31000, 21000],

    'Quantity': [2, 3, 2, 1, 4,
                 3, 2, 2, 3, 1,
                 5, 2, 2, 4, 3]
}

df = pd.DataFrame(data)

df

    Order_ID Region Product Salesperson  Sales  Quantity
0        201  North  Laptop         Raj  55000         2
1        202  South  Mobile       Priya  30000         3
2        203   East  Tablet        Aman  22000         2
3        204   West  Laptop        Neha  48000         1
4        205  North  Mobile         Raj  35000         4
5        206  South  Tablet       Priya  25000         3
6        207   East  Laptop        Aman  60000         2
7        208   West  Mobile        Neha  28000         2
8        209  North  Tablet         Raj  24000         3
9        210  South  Laptop       Priya  52000         1
10       211   East  Mobile        Aman  33000         5
11       212   West  Tablet        Neha  27000         2
12       213  North  Laptop         Raj  65000         2
13       214  South  Mobile       Priya  31000         4
14       215   East  Tablet        Aman  21000         3

In [4]:
pd.pivot_table(
    df,
    values = "Sales",
    index = "Region",
    columns = "Product",
    aggfunc = "sum"
)

Product  Laptop  Mobile  Tablet
Region
East      60000   33000   43000
North    120000   35000   24000
South     52000   61000   25000
West      48000   28000   27000

In [5]:
pd.pivot_table(
    df,
    values = "Sales",
    index = "Region",
    columns= "Product",
    aggfunc = "mean"
)

Product   Laptop   Mobile   Tablet
Region
East     60000.0  33000.0  21500.0
North    60000.0  35000.0  24000.0
South    52000.0  30500.0  25000.0
West     48000.0  28000.0  27000.0

In [8]:
pd.pivot_table(
    df,
    index = "Salesperson",
    columns = "Product",
    aggfunc = "sum"
)

            Order_ID               Quantity                    Region  \
Product       Laptop Mobile Tablet   Laptop Mobile Tablet      Laptop
Salesperson
Aman             207    211    418        2      5      5        East
Neha             204    208    212        1      2      2        West
Priya            210    416    206        1      7      3       South
Raj              414    205    209        4      4      3  NorthNorth

                                    Sales
Product          Mobile    Tablet  Laptop Mobile Tablet
Salesperson
Aman               East  EastEast   60000  33000  43000
Neha               West      West   48000  28000  27000
Priya        SouthSouth     South   52000  61000  25000
Raj               North     North  120000  35000  24000

In [10]:
pd.pivot_table(
    df,
    values = "Sales",
    index = "Salesperson",
    columns = "Region",
    aggfunc = "sum"
)

Region           East     North     South      West
Salesperson
Aman         136000.0       NaN       NaN       NaN
Neha              NaN       NaN       NaN  103000.0
Priya             NaN       NaN  138000.0       NaN
Raj               NaN  179000.0       NaN       NaN

In [11]:
pd.pivot_table(
    df,
    values = "Sales",
    columns = "Salesperson",
    aggfunc = "mean"
)

Salesperson     Aman          Neha    Priya      Raj
Sales        34000.0  34333.333333  34500.0  44750.0

In [12]:
pd.pivot_table(
    df,
    values = "Quantity",
    index = "Salesperson",
    aggfunc = "sum"
)

             Quantity
Salesperson
Aman               12
Neha                5
Priya              11
Raj                11

In [15]:
pd.pivot_table(
    df,
    values = "Sales",
    index = "Salesperson",
    aggfunc =["sum","mean"]
)

                sum          mean
              Sales         Sales
Salesperson
Aman         136000  34000.000000
Neha         103000  34333.333333
Priya        138000  34500.000000
Raj          179000  44750.000000

In [17]:
pd.pivot_table(
    df,
    values = "Sales",
    index = ["Salesperson","Region"],
    columns = "Product",
    aggfunc = "sum"
)

Product             Laptop  Mobile  Tablet
Salesperson Region
Aman        East     60000   33000   43000
Neha        West     48000   28000   27000
Priya       South    52000   61000   25000
Raj         North   120000   35000   24000

In [19]:
pd.pivot_table(
    df,
    values ="Sales",
    index = "Region",
    aggfunc = "sum"
).sort_values(by = "Sales",ascending = False)

         Sales
Region
North   179000
South   138000
East    136000
West    103000

In [25]:
pd.pivot_table(
    df,
    values = "Quantity",
    index = "Product",
    aggfunc = "sum"
).sort_values(by="Quantity",ascending= False)

         Quantity
Product
Mobile         18
Tablet         13
Laptop          8