In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("ecommerce1_data.csv.csv")

In [9]:
# Q1. Load the dataset into a Pandas DataFrame and display the first 10 rows. Also find the number of rows and columns
df.head(11)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
0,ORD116809,2024-02-07,Pooja Patel,Gurgaon,Monitor,Gaming,5.0,22061.08,0.05,104790.13,Net Banking,Delivered,25.0,3.0,12.0
1,ORD116171,2024-02-11,Vikas Sharma,Gurgaon,Headphones,Accessories,4.0,NaN,0.30,305141.62,Net Banking,Pending,31.0,1.0,3.0
2,ORD123118,2023-06-07,Nikhil Sharma,Gurgaon,Laptop,Gaming,3.0,51216.27,0.20,122919.05,Debit Card,Returned,65.0,3.0,14.0
3,ORD123757,2024-11-16,Nikhil Patel,Lucknow,Laptop,Computers,7.0,54651.12,0.05,363429.95,Credit Card,Cancelled,22.0,4.0,8.0
4,ORD101588,2023-11-24,Aarav Singh,Hyderabad,Mouse,Electronics,5.0,77021.50,0.00,385107.50,UPI,delivered,31.0,2.0,1.0
5,ORD126669,2023-07-01,Pooja Patel,Kolkata,Mouse,Electronics,5.0,114580.79,0.30,401032.76,Net Banking,Shipped,18.0,1.0,2.0
6,ORD126430,2025-02-24,Aditi Sharma,Hyderabad,Speaker,Computers,4.0,108233.71,0.25,324701.13,Credit Card,Cancelled,51.0,5.0,12.0
7,ORD110959,2024-08-23,Simran Jain,Jaipur,Smartwatch,Electronics,2.0,87304.23,0.05,165878.04,Cash,Delivered,33.0,1.0,7.0
8,ORD101676,2023-09-12,Mohit Agarwal,Chennai,Mouse,Gaming,5.0,55343.51,0.05,262881.67,Wallet,Shipped,NaN,5.0,4.0
9,ORD125221,2025-07-28,Simran Mehta,Delhi,USB Cable,Mobile,6.0,61307.59,0.15,312668.71,Net Banking,Returned,55.0,1.0,8.0
10,ORD104810,2023-04-30,Amit Patel,Surat,Router,Accessories,4.0,65797.81,0.25,197393.43,UPI,Pending,31.0,3.0,7.0

In [12]:
# Q2. Display the column names, data types, and basic information about the dataset. Which columns contain missing values?
df.columns
df.dtypes
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30250 entries, 0 to 30249
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       30250 non-null  object
 1   Order_Date     29999 non-null  object
 2   Customer_Name  29894 non-null  object
 3   City           29946 non-null  object
 4   Product        29998 non-null  object
 5   Category       30047 non-null  object
 6   Quantity       30069 non-null  float64
 7   Unit_Price     30028 non-null  float64
 8   Discount       29999 non-null  float64
 9   Sales          29945 non-null  float64
 10  Payment_Mode   29996 non-null  object
 11  Order_Status   30050 non-null  object
 12  Customer_Age   29900 non-null  float64
 13  Rating         29797 non-null  float64
 14  Delivery_Days  29947 non-null  float64
dtypes: float64(7), object(8)
memory usage: 3.5+ MB

Order_ID           0
Order_Date       251
Customer_Name    356
City             304
Product          252
Category         203
Quantity         181
Unit_Price       222
Discount         251
Sales            305
Payment_Mode     254
Order_Status     200
Customer_Age     350
Rating           453
Delivery_Days    303
dtype: int64

In [14]:
# Q3. Find the number of unique values in every column. Which columns have a relatively small number of unique values and could be useful for grouping?
df.nunique()

Order_ID         30000
Order_Date        1655
Customer_Name      160
City                73
Product             40
Category            10
Quantity            11
Unit_Price       29748
Discount             7
Sales            29690
Payment_Mode         9
Order_Status        10
Customer_Age        56
Rating               8
Delivery_Days       18
dtype: int64

In [17]:
# Q4. Find the total number of unique customers, products, cities, and categories.
df["Customer_Name"].nunique()

160

In [18]:
df["Product"].nunique()

40

In [19]:
df["City"].nunique()

73

In [20]:
df["Category"].nunique()

10

In [21]:
# Q5. Find the number of missing values in every column. Display the columns in descending order of missing values.
df.isnull().sum().sort_values(ascending = False)

Rating           453
Customer_Name    356
Customer_Age     350
Sales            305
City             304
Delivery_Days    303
Payment_Mode     254
Product          252
Order_Date       251
Discount         251
Unit_Price       222
Category         203
Order_Status     200
Quantity         181
Order_ID           0
dtype: int64

In [22]:
# Q6. Check whether the dataset contains duplicate rows. If duplicates exist, remove them and verify the result.
df.duplicated().sum()

np.int64(250)

In [23]:
df = df.drop_duplicates()

In [24]:
df.duplicated().sum()

np.int64(0)

In [29]:
# Q7. Convert Order_Date into the appropriate datetime datatype. Then find the earliest and latest order dates in the dataset.
df["Order_Date"] = pd.to_datetime(df["Order_Date"],errors = 'coerce')

C:\Users\abhis\AppData\Local\Temp\ipykernel_12140\2007026148.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [30]:
df['Order_Date'].agg(['min','max'])

min   2023-01-01
max   2025-12-31
Name: Order_Date, dtype: datetime64[ns]

In [31]:
# Q8. Find all orders where Quantity is greater than 3, Rating is less than or equal to 2, and Order_Status is 'Delivered'. How many such orders are there?
df[(df["Quantity"]>3)& (df["Rating"]<= 2) & (df["Order_Status"])]

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
1,ORD116171,2024-02-11,Vikas Sharma,Gurgaon,Headphones,Accessories,4.0,NaN,0.30,305141.62,Net Banking,Pending,31.0,1.0,3.0
4,ORD101588,2023-11-24,Aarav Singh,Hyderabad,Mouse,Electronics,5.0,77021.50,0.00,385107.50,UPI,delivered,31.0,2.0,1.0
5,ORD126669,2023-07-01,Pooja Patel,Kolkata,Mouse,Electronics,5.0,114580.79,0.30,401032.76,Net Banking,Shipped,18.0,1.0,2.0
9,ORD125221,2025-07-28,Simran Mehta,Delhi,USB Cable,Mobile,6.0,61307.59,0.15,312668.71,Net Banking,Returned,55.0,1.0,8.0
24,ORD103592,NaT,Pooja Agarwal,Indore,Laptop,Computers,5.0,85382.57,0.25,320184.64,Cash,Shipped,48.0,2.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30239,ORD116850,2024-02-10,Nikhil Sharma,Jodhpur,Keyboard,Electronics,4.0,962.49,0.20,3079.97,Debit Card,Cancelled,40.0,2.0,9.0
30245,ORD129802,2025-06-25,Simran Patel,Ajmer,SSD,Electronics,6.0,98283.87,0.15,501247.74,Wallet,Shipped,29.0,1.0,8.0
30247,ORD100860,2025-02-23,Rahul Patel,Surat,Router,Electronics,4.0,59504.97,0.30,166613.92,Credit Card,Pending,66.0,1.0,NaN
30248,ORD115795,2023-05-07,Aditi Patel,Mumbai,Webcam,Gaming,5.0,114753.68,0.10,516391.56,Net Banking,Cancelled,64.0,1.0,4.0
30249,ORD123654,2024-08-12,Rohan Gupta,Jaipur,Earbuds,Computers,6.0,111887.19,0.25,503492.36,Net Banking,Pending,31.0,2.0,4.0

In [33]:
# Q9. Display the top 10 orders based on Sales. Show only Order_ID, Customer_Name, Product, Quantity, and Sales.
df.sort_values(by="Sales",ascending = False)[["Order_ID","Customer_Name","Product","Quantity","Sales"]].head(10)

        Order_ID  Customer_Name       Product  Quantity      Sales
15776  ORD109522   Nikhil Mehta         Mouse       7.0  839697.25
25801  ORD105590    Aditi Patel    Headphones       7.0  837870.32
14481  ORD112498     Kavya Khan    power bank       7.0  837445.35
28692  ORD121566  Simran Sharma           SSD       7.0  836729.46
17085  ORD116849   Anjali Gupta        Webcam       7.0  836461.64
2721   ORD105388    Rohan Mehta        Camera       7.0  835081.03
26425  ORD127997    Anjali Jain      Keyboard       7.0  833556.36
25806  ORD113341     Vikas Khan  Mobile Phone       7.0  832639.92
1039   ORD101536  Karan Agarwal  Mobile Phone       7.0  832186.46
28185  ORD109516     Priya Jain       Printer       7.0  827839.53

In [34]:
# Q10. Find all orders where the discount is greater than 20%. Sort the result by Discount from highest to lowest.
df[df["Discount"]>0.20].sort_values(by = "Discount" ,ascending = False)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
1,ORD116171,2024-02-11,Vikas Sharma,Gurgaon,Headphones,Accessories,4.0,NaN,0.30,305141.62,Net Banking,Pending,31.0,1.0,3.0
16968,ORD120030,2024-04-08,Nikhil Gupta,Bangalore,Earbuds,Gaming,7.0,41452.41,0.30,203116.81,Credit Card,Pending,66.0,3.0,1.0
17033,ORD110204,2025-06-22,Amit Gupta,Pune,Desk,Mobile,3.0,114272.02,0.30,239971.24,Cash,Pending,63.0,4.0,1.0
17032,ORD109352,2023-04-25,Priya Jain,Pune,Earbuds,Computers,7.0,19120.54,0.30,93690.65,UPI,Cancelled,38.0,2.0,7.0
17022,ORD121129,2023-10-18,Karan Patel,Gurgaon,USB Cable,Computers,1.0,12224.76,0.30,8557.33,Credit Card,Pending,40.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17830,ORD124902,2023-07-11,Aditi Patel,Indore,Power Bank,Gaming,3.0,42826.86,0.25,96360.44,Cash,Cancelled,61.0,1.0,5.0
17822,ORD101860,2024-02-29,Sneha Gupta,Sikar,Power Bank,Gaming,5.0,106342.18,0.25,398783.17,UPI,Cancelled,50.0,4.0,3.0
6311,ORD123948,2025-10-22,Karan Mehta,Bhopal,Camera,Mobile,4.0,25740.93,0.25,77222.79,Wallet,Returned,21.0,1.0,12.0
17809,ORD127165,2024-08-16,Karan Joshi,Noida,Keyboard,Electronics,4.0,37339.57,0.25,112018.71,Cash,Cancelled,57.0,1.0,9.0
30249,ORD123654,2024-08-12,Rohan Gupta,Jaipur,Earbuds,Computers,6.0,111887.19,0.25,503492.36,Net Banking,Pending,31.0,2.0,4.0

In [7]:
# Q11. Find the 10 products with the highest average rating. Display the product name and average rating.
df.groupby("Product")["Rating"].mean().sort_values(ascending = False).head(10)

Product
desk            3.736842
hard disk       3.500000
mouse           3.448276
smartwatch      3.296296
tablet          3.178571
ssd             3.150000
power bank      3.133333
monitor         3.125000
mobile phone    3.125000
earbuds         3.105263
Name: Rating, dtype: float64

In [10]:
# Q12. Calculate the total sales generated by each Category. Sort the result from highest to lowest sales.
df.groupby("Category")["Sales"].sum().sort_values(ascending = False)

Category
Electronics    1.217991e+09
Gaming         1.208562e+09
Mobile         1.202927e+09
Computers      1.186910e+09
Accessories    1.182436e+09
gaming         2.042812e+07
accessories    1.766008e+07
computers      1.691730e+07
electronics    1.679163e+07
mobile         1.472076e+07
Name: Sales, dtype: float64

In [16]:
# Q13. Find the total quantity sold and total sales for each Product. Display the top 10 products based on total sales.
df.groupby("Product").agg({"Quantity":"sum","Sales":"sum"}).sort_values(by = "Sales",ascending = False).head(10)

            Quantity         Sales
Product
SSD           6735.0  3.168064e+08
Speaker       6764.0  3.160606e+08
Monitor       6237.0  3.132112e+08
Tablet        6372.0  3.094818e+08
Desk          6144.0  3.079382e+08
Headphones    6136.0  3.044858e+08
Smartwatch    6189.0  3.035287e+08
Camera        6236.0  3.032828e+08
Mouse         6126.0  3.027524e+08
Keyboard      6373.0  2.998599e+08

In [18]:
# Q14. Calculate the average Sales, average Rating, and average Delivery_Days for each Payment_Mode
df.groupby("Payment_Mode").agg({"Sales":"mean","Rating":"mean","Delivery_Days":"mean"})

                      Sales    Rating  Delivery_Days
Payment_Mode
Cash          201392.610925  3.020177       7.568307
Credit Card   204734.939130  3.015692       7.731410
Credit card   223912.377000  3.172414       7.666667
Debit Card    204023.203676  3.041199       7.702313
Net Banking   207930.051723  3.015237       7.575758
UPI           204801.997105  2.988001       7.603040
Wallet        204525.526292  3.013166       7.488023
debit card    229094.419014  2.788732       7.472222
upi           189945.421746  2.916667       7.238095

In [21]:
# Q15. Find the number of orders and total sales generated by each City. Which 5 cities have generated the highest sales?
df.groupby("City").agg({"Order_ID":"size","Sales":"sum"}).sort_values(by = "City",ascending=False)

            Order_ID         Sales
City
udaipur            4  4.811509e+05
udaipur           47  9.850404e+06
surat              2  5.033582e+05
surat             35  5.897893e+06
sikar              2  1.785882e+05
...              ...           ...
Bangalore       1414  2.900846e+08
Ajmer             28  5.276116e+06
Ajmer           1431  2.933350e+08
Ahmedabad         25  5.148004e+06
Ahmedabad       1438  2.846666e+08

[73 rows x 2 columns]

In [27]:
# Q16. Create a new column called Month from Order_Date. Find the total sales for each month.
df["Order_Date"]=pd.to_datetime(df["Order_Date"],errors = 'coerce')
df.groupby("Month")["Sales"].sum()

Month
1.0     4.839481e+08
2.0     4.660708e+08
3.0     5.257560e+08
4.0     4.814454e+08
5.0     4.937359e+08
6.0     4.790626e+08
7.0     5.298232e+08
8.0     4.817005e+08
9.0     4.966004e+08
10.0    5.243747e+08
11.0    4.786414e+08
12.0    4.788614e+08
Name: Sales, dtype: float64

In [28]:
df["Month"] = df["Order_Date"].dt.month_name()

In [29]:
df

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days,Month
0,ORD116809,2024-02-07,Pooja Patel,Gurgaon,Monitor,Gaming,5.0,22061.08,0.05,104790.13,Net Banking,Delivered,25.0,3.0,12.0,February
1,ORD116171,2024-02-11,Vikas Sharma,Gurgaon,Headphones,Accessories,4.0,NaN,0.30,305141.62,Net Banking,Pending,31.0,1.0,3.0,February
2,ORD123118,2023-06-07,Nikhil Sharma,Gurgaon,Laptop,Gaming,3.0,51216.27,0.20,122919.05,Debit Card,Returned,65.0,3.0,14.0,June
3,ORD123757,2024-11-16,Nikhil Patel,Lucknow,Laptop,Computers,7.0,54651.12,0.05,363429.95,Credit Card,Cancelled,22.0,4.0,8.0,November
4,ORD101588,2023-11-24,Aarav Singh,Hyderabad,Mouse,Electronics,5.0,77021.50,0.00,385107.50,UPI,delivered,31.0,2.0,1.0,November
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30245,ORD129802,2025-06-25,Simran Patel,Ajmer,SSD,Electronics,6.0,98283.87,0.15,501247.74,Wallet,Shipped,29.0,1.0,8.0,June
30246,ORD105390,2023-03-16,Kavya Mehta,Ajmer,Camera,Gaming,6.0,76303.14,0.10,412036.96,Credit Card,Returned,55.0,4.0,2.0,March
30247,ORD100860,2025-02-23,Rahul Patel,Surat,Router,Electronics,4.0,59504.97,0.30,166613.92,Credit Card,Pending,66.0,1.0,NaN,February
30248,ORD115795,2023-05-07,Aditi Patel,Mumbai,Webcam,Gaming,5.0,114753.68,0.10,516391.56,Net Banking,Cancelled,64.0,1.0,4.0,May
30249,ORD123654,2024-08-12,Rohan Gupta,Jaipur,Earbuds,Computers,6.0,111887.19,0.25,503492.36,Net Banking,Pending,31.0,2.0,4.0,August

In [30]:
df = df.drop(columns = ["Month"])

In [31]:
df

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
0,ORD116809,2024-02-07,Pooja Patel,Gurgaon,Monitor,Gaming,5.0,22061.08,0.05,104790.13,Net Banking,Delivered,25.0,3.0,12.0
1,ORD116171,2024-02-11,Vikas Sharma,Gurgaon,Headphones,Accessories,4.0,NaN,0.30,305141.62,Net Banking,Pending,31.0,1.0,3.0
2,ORD123118,2023-06-07,Nikhil Sharma,Gurgaon,Laptop,Gaming,3.0,51216.27,0.20,122919.05,Debit Card,Returned,65.0,3.0,14.0
3,ORD123757,2024-11-16,Nikhil Patel,Lucknow,Laptop,Computers,7.0,54651.12,0.05,363429.95,Credit Card,Cancelled,22.0,4.0,8.0
4,ORD101588,2023-11-24,Aarav Singh,Hyderabad,Mouse,Electronics,5.0,77021.50,0.00,385107.50,UPI,delivered,31.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30245,ORD129802,2025-06-25,Simran Patel,Ajmer,SSD,Electronics,6.0,98283.87,0.15,501247.74,Wallet,Shipped,29.0,1.0,8.0
30246,ORD105390,2023-03-16,Kavya Mehta,Ajmer,Camera,Gaming,6.0,76303.14,0.10,412036.96,Credit Card,Returned,55.0,4.0,2.0
30247,ORD100860,2025-02-23,Rahul Patel,Surat,Router,Electronics,4.0,59504.97,0.30,166613.92,Credit Card,Pending,66.0,1.0,NaN
30248,ORD115795,2023-05-07,Aditi Patel,Mumbai,Webcam,Gaming,5.0,114753.68,0.10,516391.56,Net Banking,Cancelled,64.0,1.0,4.0
30249,ORD123654,2024-08-12,Rohan Gupta,Jaipur,Earbuds,Computers,6.0,111887.19,0.25,503492.36,Net Banking,Pending,31.0,2.0,4.0

In [36]:
# Q17. Find the total sales for each Order_Status. Also calculate what percentage of total orders belong to each status.
status_summary = df.groupby("Order_Status").agg(
    total_sale = ("Sales","sum"),
    order_count = ("Sales","count"))
status_summary["Percentage"] = (status_summary["order_count"]/len(df))*100
status_summary

                total_sale  order_count  Percentage
Order_Status
 SHIPPED      2.051242e+07           93    0.307438
Cancelled     1.193796e+09         5908   19.530579
Delivered     1.194649e+09         5818   19.233058
PENDING       2.555965e+07          117    0.386777
Pending       1.207085e+09         5872   19.411570
Returned      1.170598e+09         5777   19.097521
Shipped       1.217631e+09         5873   19.414876
cancelled     1.939287e+07           86    0.284298
delivered     2.211758e+07          105    0.347107
returned      1.725019e+07          101    0.333884

In [11]:
# Q18. Compare the performance of different categories by calculating Total Sales, Average Sales, Total Quantity Sold, Average Rating, and Average Delivery Days. Which category appears to perform best overall?
category_performance = df.groupby("Category").agg(
    total_sales = ("Sales","sum"),
    average_sales =("Sales","mean"),
    sold_quantity = ("Sales","count"),
    average_rating = ("Rating","mean"),
    av_delivery_days = ("Delivery_Days","mean")
).reset_index()
category_performance

,Category,total_sales,average_sales,sold_quantity,average_rating,av_delivery_days
0,Accessories,1.182436e+09,201299.978830,5874,3.003261,7.597843
1,Computers,1.186910e+09,204322.613286,5809,3.035881,7.754983
2,Electronics,1.217991e+09,205325.541792,5932,3.007296,7.640148
3,Gaming,1.208562e+09,206133.803546,5863,3.008731,7.601970
4,Mobile,1.202927e+09,206653.055314,5821,3.024987,7.520604
5,accessories,1.766008e+07,176600.803600,100,2.802083,7.545455
6,computers,1.691730e+07,192242.068295,88,2.920455,6.932584
7,electronics,1.679163e+07,195251.468140,86,3.333333,7.141176
8,gaming,2.042812e+07,224484.827033,91,2.967033,7.505618
9,mobile,1.472076e+07,186338.741013,79,3.270270,7.987179